version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

  secnote:
    build:
      context: .
    environment:
      DB_SCHEMA: default
      DB_USER: postgres
      DB_PASSWORD: qwerty
      DB_HOST: localhost
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  database: